### ISSUE TITLE
NumerFormatException for non-integer values in highscores

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#132]
09:37:57.635 [/api/v1/games/knowns] ERROR d.m.v.s.h.HighscoreResolver - Failed to find highscore for table TheATeam.vpx: For input string: "14464454.3"
java.lang.NumberFormatException: For input string: "14464454.3"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Long.parseLong(Unknown Source)
	at java.base/java.lang.Long.parseLong(Unknown Source)
	at de.mephisto.vpin.server.util.vpreg.VPReg.readHighscores(VPReg.java:261)
	at de.mephisto.vpin.server.highscores.HighscoreResolver.readVPRegHighscore(HighscoreResolver.java:132)
	at de.mephisto.vpin.server.highscores.HighscoreResolver.readHighscore(HighscoreResolver.java:70)

**Comment by syd711** [comment]
Fixed with version >2.11.1
