### ISSUE TITLE
Improve Error Handling for Emulator Setup Errors

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#175]
Improve installer issues, so that emulator config errors are handled gracefully.

```
Caused by: java.lang.UnsupportedOperationException: Failed to determine emulator for highscores, no VPinMAME/nvram folder could be resolved (0 VPX emulators found).
	at de.mephisto.vpin.server.popper.PinUPConnector.getDefaultGameEmulator(PinUPConnector.java:91)
	at de.mephisto.vpin.server.popper.PinUPConnector.afterPropertiesSet(PinUPConnector.java:1535)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 100 common frames omitted

```

**Comment by syd711** [comment]
Fixed with 2.15.0
